# To automatically enable dependencies for Github Pages deployments:
# 1. Make sure every PRIOR line consists of '#[github-pages]'
# 2. Then run `convert-to-gh-pages.sh`

name: "ORNL Software Catalog"
author: "ORNL Open Source Software <software@ornl.gov>"
title: ORNL Software Catalog
description: "Oak Ridge National Laboratory Software Catalog"

#[github-pages]
#remote_theme: ORNL/Jekyll-ORNL-Theme@main

#baseurl: ""
url: "https://software.ornl.gov/catalog"
repo_url: "https://github.com/ORNL/ornl.github.io"

# ORNL Piwik Analytics https://analytics.ornl.gov
#piwik_id: 250

# Google Analytics ID
#google_analytics:
#  tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
#twitter:
#  username: ornl_opensource

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: ornl/ornl.github.io
plugins:
  #[github-pages]
  #- jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  #[github-pages]
  #- jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - CONTRIBUTING.md
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
    - build
    - worker.Dockerfile
