# To automatically enable dependencies for Github Pages deployments:
# 1. Make sure every PRIOR line consists of '#[github-pages]'
# 2. Then run `convert-to-gh-pages.sh`

### WEBSITE VARIABLES ###
name: "ORNL Software Catalog"
repo_url: "https://github.com/ORNL/ornl.github.io"
lab_name: "ORNL"

### SEO ###

title: ORNL Software Catalog
tagline: The hub for open-source software produced at ORNL
description: "Get the latest news and metadata about ORNL's software"
url: "https://software.ornl.gov/catalog"
author: "ORNL Open Source Software <software@ornl.gov>"
twitter:
  username: ornl
  #username: ornl_opensource

# google_site_verification: 477TVoInt3HiUgSl_hU4rb5_JrgNMKK5Rl-KPMUClpQ

# ORNL Piwik Analytics https://analytics.ornl.gov
#piwik_id: 250

# Google Analytics ID
#google_analytics:
#  tracking_id: UA-75179431-1

### GitHub Metadata -- https://github.com/jekyll/github-metadata ###
#[github-pages]
repository: ORNL/software-catalog

#[github-pages]
remote_theme: ORNL/Jekyll-ORNL-Theme@main

### JEKYLL DEFAULTS ###

#baseurl: ""

plugins:
  #[github-pages]
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  #[github-pages]
  - jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/ornl-logo.png

permalink: pretty

exclude:
  - build
  - public
  - CNAME
  - CONTRIBUTING.md
  - convert-to-gh-pages.sh
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - setup.cfg
  - worker.Dockerfile

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
